config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :experiences, only: [:show, :create, :index]

  get 'experiences/:id/details' => 'experiences#show_details', as: :details_experience

  resources :adventures
  root to: 'pages#home'

  namespace :account do
    resources :experiences
    get 'todo' => 'experiences#todo'
    get 'done' => 'experiences#done'
    get 'my_index' => 'experiences#my_index'
  end

end

app/views/shared/_analytics.html.erb
<div class="analytics">
  <span>
    <%=link_to account_todo_path, class:"hover-red" do %>
      <span id="toDoCount">
        <%= current_user.experiences_to_do_count %>
      </span>
      <i class="fa fa-heart"></i>
      <p>à vivre</p>
    <% end %>
  </span>
  <span>
    <%=link_to account_experiences_path, class:"hover-red" do %>
      <span id="doneCount">
        <%= current_user.experiences_done_count %>
      </span>
      <i class="fa fa-check"></i>
      <p>vécu</p>
    <% end %>
  </span>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style='<%= experience.adventure.picture? ? "background-image: url( #{experience.adventure.picture.url(:medium)});" : "" %>'>

  <%=link_to experiences_path() do %>
    <div class="banner-content">
      <% if @message != nil %>
        <p class="padding-60"><%= @message %></p>
      <% else %>
        <h1 class="padding-60"><%= experience.title.capitalize %></h1>
        <p>inspiré par <%=experience.inspirer.first_name%> <%= experience.inspirer.picture? ? image_tag(experience.inspirer.picture, class:'avatar') : "" %>
        </p>
      <% end %>
    </div>
  <% end %>
  <div class="banner-category <%= experience.category %>" >
    <%= experience.category.capitalize %>
  </div>
  <div id="showDetails" >
    <i class="fa fa-angle-down" ></i>
  </div>
  <div class="banner-shadow"></div>
</div>

app/views/shared/_banner_with_category.html.erb
<div class="banner" style="background-image: url(<%= experience.adventure.picture.url %>);">
  <div class="banner-content">
    <h1 class="padding-60"><%= experience.title %></h1>
    <p>inspiré par <%= image_tag(experience.inspirer.picture, class:'avatar') %></p>
  </div>
  <div class="banner-shadow"></div>
  <div class="banner-category" style="background-color: $<%=  @experience.category %>"><%= experience.category.capitalize %></div>
</div>

app/views/shared/_card.html.erb
<!-- Experience title-->
<div class="experience-card-title">
  <%= experience.title %>
</div>
<!-- Experience Block with image -->
<div class="experience-card-block">
  <% if experience.adventure.picture_file_name %>
    <!-- Link to details experience -->
    <%=link_to details_experience_path(id: experience), class:'link' do %>
      <div class= 'experience-card-block-link' style="background-image: url(<%= experience.adventure.picture.url(:medium) %>);">
      </div>
    <% end %>
    <!-- Experience status : done, to do -->
    <div class="experience-card-block-status">
      <% if experience.done %>
        <i class="fa fa-heart padding-horizontal"></i>
      <% else %>
        <i class="fa fa-check padding-horizontal"></i>
      <% end %>
    </div>
    <!-- Cross - Heart - Check Board -->
    <!--<div class="board bottom-fit bg-transparent">
      <%= render 'shared/experience_selection_board', experience: experience %>
    </div>-->
  <% end %>
</div>
<!-- Inspired By -->
<div class="experience-card-user">
  <% if experience.actor %>
    <span>
      <em>inspiré par </em> <%= image_tag(experience.actor.picture, class:'avatar') %>
    </span>
  <% else %>
    <span>
      <em>créé par </em> <%= image_tag(experience.inspirer.picture, class:'avatar') %>
    </span>
  <% end %>
</div>

app/views/shared/_experience_selection_board.html.erb
<!-- Experience Selection board : Cross - Hear - Check Board -->
<div class="board-game">
  <!-- Heart Item : To do -->
  <div class="board-game-item">
    <%=link_to experiences_path(id: experience, status: "to_do"), class:"hover-red", method: :post, remote: true do %>
      <%= image_tag "heart.png", class: "img-btn" %>
      <!-- <i class="fa fa-heart"></i> -->
    <% end %>
     <div id="toDoCount">
        <%= current_user.experiences_to_do_count %>
      </div>
      <p>Expériences à vivre</p>
  </div>


  <!-- Check Item : Done -->
  <div class="board-game-item">
   <%=link_to experiences_path(id: experience, status: "done"), class:"hover-red", method: :post, remote: true do %>
      <%= image_tag "check.png", class: "img-btn" %>
      <% end %>
    <div id="doneCount">
      <%= current_user.experiences_done_count %>
    </div>
     <!--  <i class="fa fa-check"></i> -->
      <p>Expériences vécues</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footbar.html.erb
<!-- <div class="board-item">
  <%= link_to root_path do %>
    <i class="fa fa-star"></i>
    <div class="board-item-text">Sélection</div>
  <% end %>
</div> -->
<div class="board-item">
   <%= link_to image_tag('idea.png'), experiences_path, class: "img-btn" %>
    <br>
    <div class="board-item-text">Trouver des idées</div>
</div>
<!-- <div class="board-item">
  <%= link_to account_todo_path do %>
    <i class="fa fa-list"></i><br>
    <div class="board-item-text">Ma to do</div>
  <% end %>
</div> -->
<div class="board-item">
  <%= link_to image_tag('moi.png'), account_experiences_path, class: "img-btn" %>
    <br>
    <div class="board-item-text">Moi</div>
</div>

<div class="board-item">
     <%= link_to image_tag('create.png'), new_adventure_path, class: "img-btn" %>
    <br>
    <div class="board-item-text">Créer une expérience</div>
</div>

app/views/shared/_list_item.html.erb
<!-- Experience title-->
<div class="list-item" style="background-image: url('<%= experience.adventure.picture.url(:medium) %>');" data-target="<%=experience.id%>">
  <div class="list-item-content"><%= experience.title %></div>
  <div class ="list-item-category <%=experience.category%>"></div>
  <div class="banner-shadow"></div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon navbar-wagon-absolute">
  <div class="navbar-wagon-container">
    <ul class="list-unstyled list-inline">
      <li>
        <div class="navbar-wagon-logo">
          <%= link_to image_tag('Woom_logo_white.png'), root_path %>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="pull-right">
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <% if current_user.picture? %>

                <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% else %>
              <% end %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-user"></i> <%= t ".profile", default: "Profil" %>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
                  <% end %>
              </li>
              </ul>
            </div>
          </div>
        </li>
        <% else %>
          <li class="pull-right">
            <%= link_to t(".sign_in", default: "connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
          <li class="pull-right">
            <hr>
          </li>
          <li class="pull-right">
            <%= link_to t(".sign_in", default: "inscription"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_navbar_bootstrap.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Moody</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link1</a></li>
        <li><a href="#">Link2</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navbar_slide.html.erb
<!-- Navigation -->
<nav id="slide-menu">
  <ul>
    <li class="timeline">Timeline</li>
    <li class="events">Events</li>
    <li class="calendar">Calendar</li>
    <li class="sep settings">Settings</li>
    <li class="logout">Logout</li>
  </ul>
</nav>
<!-- Content panel -->
<div id="content">
  <div class="menu-trigger"></div>
  <h1>iOS style sliding menu</h1>
  <p>Here's an easy way to create an iOS style, side sliding menu.</p>
</div>

app/views/shared/_patchwork.html.erb
<h1>TODO</h1>

app/views/shared/_show.html.erb
<!-- Experience Main Informations View -->
<div class="container">
  <div class="row">
    <div class="category">
      <%= @experience.category %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="experience-card" id="experience_<%= @experience.id %>">
        <%= render 'shared/card', experience: @experience %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_show_details.html.erb
<!-- Description -->
<div class="experience-details-card bg-white">
  <div class="experience-details-card-item">
    <span>
      <i class="fa fa-align-justify"></i>
      <% if experience.adventure.description!="" %>
        <span><%=experience.adventure.description %></span>
      <% else %>
        <span>Non précisé</span>
      <% end %>
    </span>
  </div>

  <div class="experience-details-card-item">
    <!-- Start date -->
    <i class="fa fa-calendar"></i>
    <% if experience.adventure.start_date %>
      <span><%= experience.adventure.start_date.strftime("%d-%m-%Y") %></span>
    <% else %>
      <span>Non précisé</span>
    <% end %>
  </div>
    <!-- End date -->
  <div class="experience-details-card-item">
    <i class="fa fa-calendar"></i>
    <% if experience.adventure.end_date %>
      <span><%= experience.adventure.end_date.strftime("%d-%m-%Y") %></span>
    <% else %>
      <span>Non précisé</span>
    <% end %>
  </div>
  <!-- Address -->
  <div class="experience-details-card-item">
    <i class="fa fa-compass"></i>
    <% if experience.adventure.address %>
      <span><%= experience.adventure.address %></span>
    <% else %>
      <span>Non précisé</span>
    <% end %>
  </div>
</div>