config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :experiences, only: [:show, :create, :index]

  get 'experiences/:id/details' => 'experiences#show_details', as: :details_experience

  resources :adventures
  root to: 'pages#home'

  namespace :account do
    resources :experiences
    get 'todo' => 'experiences#todo'
    get 'done' => 'experiences#done'
    get 'my_index' => 'experiences#my_index'
  end

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :experiences

  # Validations
  validates :category, presence: true
  validates :title, presence: true
  validates :user, presence: true


  # Create global variable
  CATEGORIES = ['sweetlife', 'culture', 'cinéma', 'balade', 'la vie en rose', 'spectacle', 'musique', 'voyage', 'exposition', 'sensation', 'fun', 'sport', 'plaisir', 'spiritualité', 'food', 'engagement']


  # Add paperclip picture
  has_attached_file :picture,
    styles: { medium: "500x500>", thumb: "200x200>" }

    # Validation for picture
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new]
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]

  def index
    # @adventures = Adventure.search(params[:search])
    if params[:search]
      @adventures = Adventure.where("address like ?", "%#{params[:search]}%")
    else
      @adventures = Adventure.all
    end
    # adventures_with_coordinates = @adventures.select {|adventure| adventure.latitude && adventure.longitude}
    # @markers = Gmaps4rails.build_markers(adventures_with_coordinates) do |adventure, marker|
    #   marker.lat adventure.latitude
    #   marker.lng adventure.longitude
  end

  def new
    @adventure = Adventure.new
  end

  def create
    # Récupérer les paramètres de l'aventure créée
    @adventure = Adventure.new(adventure_params)
    @adventure.user = current_user
    if params[:adventure][:status][:status] == "S'en souvenir"
      status = "done"
    elsif params[:adventure][:status][:status] == "A vivre"
      status = "to_do"
    end
    @experience = Experience.new(adventure: @adventure, inspirer: current_user, status: status)

    # # Associer un utilisateur à l'aventure
    # if user_signed_in?
    #   @adventure.user = current_user
    # else
    #   @adventure.token = GENERATE_TOKEN
    #   cookies[:temporary_exp_token] = @adventure.token
    # end

    # Si l'expérience passe les validation, l'enregistrer dans la db
    # et rediriger sur la vue show de l'expérience
    if @adventure.save
      if @experience.save
        redirect_to experience_path(@experience)
      end
    else
      render :new # renvoie le formulaire de création de l'aventure
    end
  end

  def show
    #@adventure_coordinates = { lat: @adventure.latitude, lng: @adventure.longitude }
  end


  def edit
    if @adventure.token == cookies[:temporary_exp_token]
      display_validate_past_adventure
    else
      display_classical_edit_form
    end
  end

  def update
    if @adventure.update(adventure_params)
      redirect_to adventures_path(@adventure)
    else
      render :edit
    end
  end

  def destroy
    @adventure = Adventure.find(params[:id])
    @adventure.destroy
    redirect_to adventures_path
  end

  private

  def adventure_params
    params.require(:adventure).permit(
      :title,
      :category,
      :description,
      :picture,
      :start_date,
      :end_date,
      :address,
      :duration
    )
  end

  def set_adventure
    @adventure = Adventure.find(params[:id])
  end

  def display_validate_past_adventure

  end

  def display_classical_edit_form

  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/views/adventures/_form.html.erb
<div class="form">
  <%= simple_form_for(@adventure) do |f| %>
    <div class="container" >
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <%= f.error_notification %>
          <%= f.input :title, label: false, placeholder:"Faire un road trip en combi..."%>
          <%= f.input :category, label: false, as: :select, collection: Adventure::CATEGORIES, prompt: "Choisissez une catégorie" %>
          <%= f.input :picture, label: false %>
          <%= f.input :description, label: false, placeholder: "Description" %>
          <%= f.input :address, label: false, placeholder: "Adresse" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5 col-xs-offset-1">
          <%= f.input :start_date, label:false, placeholder: "Début", as: :string, input_html: {class: 'datetime'}%>
        </div>
        <div class="col-xs-5">
          <%= f.input :end_date, label:false, placeholder: "Fin", as: :string, input_html: {class: 'datetime'}%>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 text-center inline">
          <%= f.simple_fields_for :status do |ff| %>
            <div class="radio-button">
              <%= ff.input :status, label: false, as: :radio_buttons, checked: 'A vivre', collection: ['A vivre',"S'en souvenir",] %>
            </div>
          <% end %>
          <%= f.button :submit, "Créez", class: 'ghost-btn-white' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= content_for :after_js do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $("#datepicker").datepicker();
    });
  <% end %>
<% end %>

app/views/adventures/index.html.erb
<h1 class="text-center">Toutes vos expériences</h1>
<div class="text-center padded">
  <%= link_to "Create a adventure", new_adventure_path, class: "ghost-btn-grey" %>
</div>
  <div class = "container">
    <div class = "row" >
      <% @adventures.each do |adventure| %>
        <div class="col-xs-12 no-padding text-center">
            <%= link_to adventure.title, adventure_path(adventure) %>
        </div>
      <% end %>
    </div>
  </div>

app/views/adventures/new.html.erb
<div class="bg-deco bg-deco-new-adv">
  <div class="text-center margin-footbar">
    <h2>Créez une nouvelle expérience</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/adventures/show.html.erb
<div class= "text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h3><%= @adventure.title %></h2>
          <%= image_tag @adventure.picture %>
          <p><%= @adventure.category %></p>
          <p><%= @adventure.description %></p>
          <p><%= @adventure.address %></p>
          <p><%= @adventure.start_date %></p>
          <p><%= @adventure.end_date %></p>
          <p><%= @adventure.duration %></p>
      </div>
    </div>
   </div>
    <%= link_to 'Edit', edit_adventure_path(@adventure) %>
    <%= link_to 'list', adventures_path(@adventure) %>
</div>

<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <script>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });

      // google.maps.event.addDomListener(window, 'load', function() {
      //   initializeAutocomplete('user_input_autocomplete_address');
      // });

      // function initializeAutocomplete(id) {
      //   var element = document.getElementById(id);
      //   if (element) {
      //     var autocomplete = new google.maps.places.Autocomplete(element, { types: ['geocode'] });
      //     google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
      //   }
      // }

      // function onPlaceChanged() {
      //   var place = this.getPlace();

      //   // console.log(place);  // Uncomment this line to view the full object returned by Google API.

      //   for (var i in place.address_components) {
      //     var component = place.address_components[i];
      //     for (var j in component.types) {  // Some types are ["country", "political"]
      //       var type_element = document.getElementById(component.types[j]);
      //       if (type_element) {
      //         type_element.value = component.long_name;
      //       }
      //     }
      //   }
      // }

    })
  </script>
<% end %>

<%# content_for(:after_js) do %>
  <%#= javascript_tag do %>
    <!-- $(document).ready(function() {
      var coord = <%= raw @adventure_coordinates %>;
      alert('Adventure coordinates are ' + coord.lat + ', ' + coord.lng');
    }); -->
  <%# end %>
<%# end %>